### ISSUE TITLE
 Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by pankaj-ag** [facebookarchive/react-native-custom-components#16]
![image](https://user-images.githubusercontent.com/10670690/29730264-260694ec-89fd-11e7-8ae1-f33ce9356c93.png)

**Comment by pankaj-ag** [comment]
![image](https://user-images.githubusercontent.com/10670690/29730778-45656ff0-89ff-11e7-824d-b107e439bf61.png)
 Please help me to figure out this

**Comment by AnisDerbel** [comment]
You have to change  few things in the Library :
 PropTypes is deprecated from React , you have to use a separate library (npm install --save prop-types) and then you import it in the file **NavigatorBreadcrumbNavigationBar** (import PropTypes from 'prop-types';) and remove the PropTypes import from React.

**Comment by threesquared** [comment]
Why does [this line](https://github.com/facebookarchive/react-native-custom-components/blob/master/src/NavigatorBreadcrumbNavigationBar.js#L96) still use the deprecated `React.PropTypes` and not the imported`PropTypes` module?

**Comment by pankaj-ag** [comment]
Thanks, @AnisDerbel.
I tried that but then I got the second error  *React.createClass is not a function*. 
That's why I have to create this issue.

**Comment by threesquared** [comment]
This pr seems to fix the issue for me https://github.com/facebookarchive/react-native-custom-components/pull/14

**Comment by pankaj-ag** [comment]
But why they are not merging it. Anyway,'s thank you @threesquared

**Comment by iyawnis** [comment]
I am getting this error, 

   ```
 TypeError: Cannot read property 'shape' of undefined

      at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBar.js:300:425)
      at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/Navigator.js:44:38)
      at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/CustomComponents.js:28:15)
```
```

    "prop-types": "^15.6.0",
    "react": "=16.0.0",
    "react-native-deprecated-custom-components": "=0.1.1",
    "react-native": "=0.48.4",
```

Any ideas what I can do about it ?

**Comment by DanielRuf** [comment]
Confirmed. The deprecated package does not include the latest version with the bugfix.
