### ISSUE TITLE
What happen with with Error?

### ISSUE THREAD

**Issue by thiensubs** [facebookarchive/react-native-custom-components#5]
This is my error:
```
error: bundling: SyntaxError: /Users/thiensubs/Documents/timwifichua-react-native/node_modules/react-native-custom-components/index.js: Unexpected token, expected { (1:7)
> 1 | export Button from './src/components/Button';
    |        ^
  2 | export ToggleButton from './src/components/ToggleButton';
  3 | export HtmlView from './src/components/HtmlView';
  4 | export InputEditor from './src/components/InputEditor';
    at Parser.pp$5.raise (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:4443:13)
    at Parser.pp.unexpected (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:1755:8)
    at Parser.pp.expect (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:1743:33)
    at Parser.pp$1.parseExportSpecifiers (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:2822:8)
    at Parser.pp$1.parseExport (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:2650:28)
    at Parser.parseExport (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:5873:20)
    at Parser.pp$1.parseStatement (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:1878:74)
    at Parser.parseStatement (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:5795:22)
    at Parser.pp$1.parseBlockBody (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:2262:21)
    at Parser.pp$1.parseTopLevel (/Users/thiensubs/Documents/timwifichua-react-native/node_modules/babylon/lib/index.js:1772:8)
Bundling `index.ios.js`  96.2% (406/414), failed.
```
Please help me?

**Comment by joshfester** [comment]
+1 I'm getting the same error

**Comment by joshfester** [comment]
@thiensubs I fixed this by uninstalling, and then installing via 'react-native-deprecated-custom-components' instead of 'react-native-custom-components'. Change any import statements to use the new name as well.
